/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AskRouteImport } from './routes/ask'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LunchCardRouteImport } from './routes/lunch-card'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ScriptureRouteImport } from './routes/scripture'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAppealsRouteImport } from './routes/admin.appeals'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminLunchCardsRouteImport } from './routes/admin.lunch-cards'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppServiceRouteImport } from './routes/app.$service'
import { Route as CallConversationIdRouteImport } from './routes/call.$conversationId'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AdminConversationsIndexRouteImport } from './routes/admin.conversations.index'
import { Route as AdminConversationsIdRouteImport } from './routes/admin.conversations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LunchCardRoute = LunchCardRouteImport.update({
  id: '/lunch-card',
  path: '/lunch-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptureRoute = ScriptureRouteImport.update({
  id: '/scripture',
  path: '/scripture',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppealsRoute = AdminAppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLunchCardsRoute = AdminLunchCardsRouteImport.update({
  id: '/lunch-cards',
  path: '/lunch-cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/app/$service',
  path: '/app/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const CallConversationIdRoute = CallConversationIdRouteImport.update({
  id: '/call/$conversationId',
  path: '/call/$conversationId',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsIndexRoute = AdminConversationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConversationsRoute,
} as any)
const AdminConversationsIdRoute = AdminConversationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminConversationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/lunch-card': typeof LunchCardRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/scripture': typeof ScriptureRoute
  '/services': typeof ServicesRoute
  '/admin/appeals': typeof AdminAppealsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/admin/lunch-cards': typeof AdminLunchCardsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$service': typeof AppServiceRoute
  '/call/$conversationId': typeof CallConversationIdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/conversations/$id': typeof AdminConversationsIdRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/lunch-card': typeof LunchCardRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/scripture': typeof ScriptureRoute
  '/services': typeof ServicesRoute
  '/admin/appeals': typeof AdminAppealsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/lunch-cards': typeof AdminLunchCardsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$service': typeof AppServiceRoute
  '/call/$conversationId': typeof CallConversationIdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin': typeof AdminIndexRoute
  '/admin/conversations/$id': typeof AdminConversationsIdRoute
  '/admin/conversations': typeof AdminConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/chat': typeof ChatRoute
  '/lunch-card': typeof LunchCardRoute
  '/profile': typeof ProfileRoute
  '/recovery': typeof RecoveryRoute
  '/scripture': typeof ScriptureRoute
  '/services': typeof ServicesRoute
  '/admin/appeals': typeof AdminAppealsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/admin/lunch-cards': typeof AdminLunchCardsRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/$service': typeof AppServiceRoute
  '/call/$conversationId': typeof CallConversationIdRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/conversations/$id': typeof AdminConversationsIdRoute
  '/admin/conversations/': typeof AdminConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ask'
    | '/chat'
    | '/lunch-card'
    | '/profile'
    | '/recovery'
    | '/scripture'
    | '/services'
    | '/admin/appeals'
    | '/admin/applications'
    | '/admin/conversations'
    | '/admin/lunch-cards'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/app/$service'
    | '/call/$conversationId'
    | '/oauth/consent'
    | '/admin/'
    | '/admin/conversations/$id'
    | '/admin/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/chat'
    | '/lunch-card'
    | '/profile'
    | '/recovery'
    | '/scripture'
    | '/services'
    | '/admin/appeals'
    | '/admin/applications'
    | '/admin/lunch-cards'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/app/$service'
    | '/call/$conversationId'
    | '/oauth/consent'
    | '/admin'
    | '/admin/conversations/$id'
    | '/admin/conversations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ask'
    | '/chat'
    | '/lunch-card'
    | '/profile'
    | '/recovery'
    | '/scripture'
    | '/services'
    | '/admin/appeals'
    | '/admin/applications'
    | '/admin/conversations'
    | '/admin/lunch-cards'
    | '/admin/messages'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/app/$service'
    | '/call/$conversationId'
    | '/oauth/consent'
    | '/admin/'
    | '/admin/conversations/$id'
    | '/admin/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  ChatRoute: typeof ChatRoute
  LunchCardRoute: typeof LunchCardRoute
  ProfileRoute: typeof ProfileRoute
  RecoveryRoute: typeof RecoveryRoute
  ScriptureRoute: typeof ScriptureRoute
  ServicesRoute: typeof ServicesRoute
  AppServiceRoute: typeof AppServiceRoute
  CallConversationIdRoute: typeof CallConversationIdRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lunch-card': {
      id: '/lunch-card'
      path: '/lunch-card'
      fullPath: '/lunch-card'
      preLoaderRoute: typeof LunchCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripture': {
      id: '/scripture'
      path: '/scripture'
      fullPath: '/scripture'
      preLoaderRoute: typeof ScriptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appeals': {
      id: '/admin/appeals'
      path: '/appeals'
      fullPath: '/admin/appeals'
      preLoaderRoute: typeof AdminAppealsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lunch-cards': {
      id: '/admin/lunch-cards'
      path: '/lunch-cards'
      fullPath: '/admin/lunch-cards'
      preLoaderRoute: typeof AdminLunchCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/$service': {
      id: '/app/$service'
      path: '/app/$service'
      fullPath: '/app/$service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call/$conversationId': {
      id: '/call/$conversationId'
      path: '/call/$conversationId'
      fullPath: '/call/$conversationId'
      preLoaderRoute: typeof CallConversationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations/': {
      id: '/admin/conversations/'
      path: '/'
      fullPath: '/admin/conversations/'
      preLoaderRoute: typeof AdminConversationsIndexRouteImport
      parentRoute: typeof AdminConversationsRoute
    }
    '/admin/conversations/$id': {
      id: '/admin/conversations/$id'
      path: '/$id'
      fullPath: '/admin/conversations/$id'
      preLoaderRoute: typeof AdminConversationsIdRouteImport
      parentRoute: typeof AdminConversationsRoute
    }
  }
}

interface AdminConversationsRouteChildren {
  AdminConversationsIdRoute: typeof AdminConversationsIdRoute
  AdminConversationsIndexRoute: typeof AdminConversationsIndexRoute
}

const AdminConversationsRouteChildren: AdminConversationsRouteChildren = {
  AdminConversationsIdRoute: AdminConversationsIdRoute,
  AdminConversationsIndexRoute: AdminConversationsIndexRoute,
}

const AdminConversationsRouteWithChildren =
  AdminConversationsRoute._addFileChildren(AdminConversationsRouteChildren)

interface AdminRouteChildren {
  AdminAppealsRoute: typeof AdminAppealsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminConversationsRoute: typeof AdminConversationsRouteWithChildren
  AdminLunchCardsRoute: typeof AdminLunchCardsRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppealsRoute: AdminAppealsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminConversationsRoute: AdminConversationsRouteWithChildren,
  AdminLunchCardsRoute: AdminLunchCardsRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  ChatRoute: ChatRoute,
  LunchCardRoute: LunchCardRoute,
  ProfileRoute: ProfileRoute,
  RecoveryRoute: RecoveryRoute,
  ScriptureRoute: ScriptureRoute,
  ServicesRoute: ServicesRoute,
  AppServiceRoute: AppServiceRoute,
  CallConversationIdRoute: CallConversationIdRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
